.TH DWMBLOCKS 1 dwmblocks\-VERSION
.SH NAME
dwmblocks
.SH SYNOPSIS
.B dwmblocks
.RB [ \-\-help ]\ [ \-\-version ]
.RB [ \-\-all ]\ [ \-\-restart ]\ [ \-\-list ]\ [ \-\-update\ block ]
.SH DESCRIPTION
dwmasyncblocks is an asynchronous status bar for dwm. It is partitioned in blocks,
where each block runs asynchronuusly (thus the bar does not "freeze" whenever a block
takes time to update). It has clickable blocks, where using the environemnt variable
"BLOCK_BUTTON", the scripts can respond to mouse clicks, giving you endless possibilities
for customization. The blocks update either by the given period at the config.h file,
or by giving dwmblocks the corresponding block signal (SIGRTMIN+signal_number).
.P
Run with no arguments, dwmblocks starts the status bar daemon. Run with one of the
options below, it instead acts as a client, signalling the already running daemon
and exiting.

.SH OPTIONS
.TP
.B \-\-help
prints a help prompt to stdout, then exits.
.TP
.B \-\-version
prints version information to stdout, then exits.
.TP
.B \-\-all
updates all blocks in the running daemon.
.TP
.B \-\-restart
restarts the running daemon.
.TP
.B \-\-list
prints the configured block names to stdout, one per line.
.TP
.B \-\-update \fIblock\fR
updates the block with the given name in the running daemon.

.SH EXAMPLE
To update the block with the name volume, you just have to run `dwmblocks --update volume`.

.SH USAGE
To use dwmblocks is straightforward. You just need to start it on the background along dwm.
.SH CUSTOMIZATION
dwmblocks is customized by creating a custom config.h and (re)compiling the source
code. This keeps it fast, secure and simple.
.SH SIGNALS
.TP
.B SIGRTMIN + BLOCK_SIG_NO
Updates the block with the corresponding signal number.
.TP
.b SIGUSR1
Updates all blocks.
.TP
.B SIGTERM 
Cleanly terminate the dwmblocks process.
.TP
.B SIGINT 
Cleanly terminate the dwmblocks process.
.SH SEE ALSO
.BR dwm (1),
.BR st (1),
.SH BUGS
Inform me of any bugs on the github page: https://github.com/dimgerasimou/dwmasyncblocks.git
